import = [
    # "/home/johnmelrs/.config/alacritty/catppuccin-mocha.toml"
    "/home/johnmelrs/.config/alacritty/alacritty-themes/themes/kanagawa_wave"
  ]

[env]
TERM = "xterm-256color"

[window.padding]
x = 24
y = 24

[font]
size = 10
normal = { family = "FiraCode Nerd Font" }
